# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageControl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14MessageControl.proto\"B\n\rUploadRequest\x12\x0c\n\x04UUID\x18\x01 \x01(\t\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x12\n\nRemainTime\x18\x03 \x01(\x05\"!\n\x0eUploadResponse\x12\x0f\n\x07Message\x18\x01 \x01(\t\"\x1c\n\x0c\x46\x65tchRequest\x12\x0c\n\x04UUID\x18\x01 \x01(\t\" \n\rFetchResponse\x12\x0f\n\x07Message\x18\x01 \x01(\t2g\n\x0eMessageControl\x12+\n\x06Upload\x12\x0e.UploadRequest\x1a\x0f.UploadResponse\"\x00\x12(\n\x05\x46\x65tch\x12\r.FetchRequest\x1a\x0e.FetchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageControl_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPLOADREQUEST']._serialized_start=24
  _globals['_UPLOADREQUEST']._serialized_end=90
  _globals['_UPLOADRESPONSE']._serialized_start=92
  _globals['_UPLOADRESPONSE']._serialized_end=125
  _globals['_FETCHREQUEST']._serialized_start=127
  _globals['_FETCHREQUEST']._serialized_end=155
  _globals['_FETCHRESPONSE']._serialized_start=157
  _globals['_FETCHRESPONSE']._serialized_end=189
  _globals['_MESSAGECONTROL']._serialized_start=191
  _globals['_MESSAGECONTROL']._serialized_end=294
# @@protoc_insertion_point(module_scope)
